services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço para a aplicação FastAPI
  app:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/dbname"

# Volume para persistir os dados do PostgreSQL
volumes:
  postgres_data: